kbuilder_django/KB/urls.py
from django.urls import path

from . import views

app_name = 'KB'
urlpatterns = [
    # ex: /KB/
    path('', views.index, name='index'),\
    path('logs/', views.logs, name='logs'),\
    path('upload_simple/', views.simple_upload, name='simple_upload'),\
    path('upload_model/', views.model_form_upload, name='model_form_upload')
]

kbuilder_django/kbuilder_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),\
    path('KB/', include('KB.urls'))
]

kbuilder_django/KB/models.py
import datetime
from django.db import models
from django.utils import timezone
  
class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

kbuilder_django/KB/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 28 20:24:00 2019

@author: weetee
"""

from django import forms
from .models import Document

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('description', 'document', )

kbuilder_django/KB/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.core.files.storage import FileSystemStorage

from .forms import DocumentForm
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync

import sys
from io import StringIO
from .websocket_send import send_text
from kbuilder.src.KB_funcs import KB_Bot
from kbuilder.src.utils import Config
import asyncio

config = Config()
bot = KB_Bot()
event_loop = asyncio.new_event_loop()
#channel_layer = get_channel_layer()
#async_to_sync(channel_layer.group_send)('message_group', {'type':'receive',\
#             'message': "done"})
class Capturing(list):
    def __enter__(self):
        self._stdout = sys.stdout
        sys.stdout = self._stringio = StringIO()
        return self
    def __exit__(self, *args):
        self.extend(self._stringio.getvalue().splitlines())
        del self._stringio    # free up some memory
        sys.stdout = self._stdout

def logs(request):
    """Returns `JsonResponse` object"""

    # you can change the request method in the following condition.
    # I dont know what you're dealing with.
    if request.is_ajax() and request.method == 'GET':
        # main logic here setting the value of resp_data

        resp_data = {
            'html': 'stuff',
            # more data
        }

        return JsonResponse(resp_data, status=200)

def index(request):
    if request.method == 'POST':
        print("POST", request.POST)
        if 'file-upload' in request.POST:
            form = DocumentForm(request.POST, request.FILES)
            if form.is_valid():
                obj = form.save()
                send_text("Processing, this may take a while, please wait...", event_loop)
                with open(obj.document.path, 'r', encoding='utf8') as f:
                    preview = f.read()[:300]
                config.text_file = obj.document.path
                bot.__init__(args=config, restart=True)
                print("filename: ", bot.filename)
                print("modelname: ", config.state_dict)
                form = DocumentForm()
                return render(request, 'KB/index.html', {'preview': preview,\
                                                         'form': form,\
                                                         'filename': bot.filename,\
                                                         'modelname': config.state_dict,\
                                                         'message': "%s uploaded and processed. Please load model with button below." % bot.filename})
        
        elif 'query' in request.POST:
            query = request.POST.get('query-text', None)
            ans = bot.ask(query)
            send_text("Done", event_loop)
            return render(request, 'KB/index.html', {'ans': ans,\
                                                     'filename': bot.filename,\
                                                     'message': "Query processed."})
    
        else:
            form = DocumentForm()
            return render(request, 'KB/index.html', {'form': form,\
                                                     'message':'Error please try again'})
    else:
        form = DocumentForm()
        return render(request, 'KB/index.html', {'form': form,\
                                                 'message': "Please upload file below"})
            
 
def simple_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'KB/simple_upload.html', {
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'KB/simple_upload.html')

def model_form_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('KB')
    else:
        form = DocumentForm()
    return render(request, 'KB/model_form_upload.html', {
        'form': form
    })
    

kbuilder_django/KB/templates/KB/index.html
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Knowledge Builder</title>
	<style>
	H1 {color:blue;}
	p {color:purple;}
	h3 {color:#166C09;}
	</style>
  </head>

  <body>
	<H1>Knowledge Builder</H1>
	<P>
	<BR>

<button onclick="start()">Test Websocket</button>
<br/>
<label for="Ans">System message:</label>
	<br/>
	<textarea style="width:1000px; height:50px; font-size:15px;" rows="30" cols="100" id="lbl" name="lbl" readonly>
{{message}}
	</textarea>
<hr>

<h3> Upload text file </h3>
    <label for="file-upload">Upload document file (.txt) for building Knowledge Base</label>
<form id='form1' method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" name='file-upload'>Upload file</button>
  </form>

{% if preview %}
	<label for="rawtext">Text Preview:</label>
	<br/>
	<textarea id="rawtext" rows="10" cols="100">
	{{preview}}
	</textarea></p>
{% endif %}


File saved path: <div id="filename">{{filename}}</div>
<br/>
Model saved path: <div id="modelname">{{modelname}}</div>
<button style="width:175px; height:30px; font-size:15px;" onclick="load_file(document.getElementById('modelname').innerText)" >Load this model</button><div id="mod_status"></div>

<hr>
<h3> Ask a question </h3>
<label for="text">Input Question:</label>
<input style="width:1000px; height:30px; font-size:15px;" type="text" id="query-text" name="query-text">
<button style="width:75px; height:30px; font-size:15px;" onclick="query(document.getElementById('query-text').value)" >Query</button>

    <P>
	<label for="ans">Answer:</label>
	<br/>
	<textarea style="width:1000px; height:30px; font-size:15px;" rows="30" cols="100" id="answer" readonly>
	</textarea>
	
    <p>

<hr>
<h3> Find specific Subject and/or Predicate and/or Object </h3>
<label for="text">Input Subject:</label>
<input style="width:300px; height:30px; font-size:15px;" type="text" id="subject" name="subject">
<br/>
<label for="text">Input Predicate:</label>
<input style="width:300px; height:30px; font-size:15px;" type="text" id="predicate" name="predicate">
<br/>
<label for="text">Input Object:</label>
<input style="width:300px; height:30px; font-size:15px;" type="text" id="object" name="object">
<br/>
<button style="width:175px; height:30px; font-size:15px;" onclick="send_triplet(document.getElementById('subject').value,
										document.getElementById('predicate').value,
										document.getElementById('object').value)" >Find</button>
<br/>
<p>
<label for="ans1">Answer:</label>
<br/>
<textarea style="width:1000px; height:300px; font-size:15px;" rows="100" cols="120" id="matched_triplets" readonly>
</textarea>

<script>
    var socket = new WebSocket('ws://' + window.location.host + '');
 
    socket.onopen = function open() {
      console.log('WebSocket connection created.');
    };
 
    socket.onmessage = function message(event) {
      	console.log("data from socket:" + event.data);
	msg = JSON.parse(event.data);
	switch(msg.label) {
	case "msg":
		lbl.innerText = msg.text;
		break;
	case "query":
		answer.innerText = msg.text;
		break;
	case "model_status":
		mod_status.innerText = msg.text;
		break;
	case "triplet":
		matched_triplets.innerText = msg.text;
		break;
};
    };
 
    if (socket.readyState == WebSocket.OPEN) {
      socket.onopen();
    }
    function start()
    {
      socket.send('{"text": "Websocket working!", "label":"msg"}');
    }
    function stop() {
      socket.send('{"text": "stop", "label":"msg"}');
    }
function query(text) {
        socket.send('{"text": "' + text + '", "label":"query"}');
    }
function load_file(filename) {
        socket.send('{"text": "' + filename+ '", "label":"filename"}');
    }
function send_triplet(subject, predicate, object) {
	socket.send('{"text": "' + subject + '@' + predicate + '@' + object + '", "label":"triplet"}');
    }

</script>
</html>


kbuilder_django/KB/templates/KB/model_form_upload.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}

kbuilder_django/KB/templates/KB/simple_upload.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

  <p><a href="{% url 'KB:index' %}">Return to home</a></p>
{% endblock %}

kbuilder_django/KB/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Simple File Upload</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>